### PR TITLE
Add 'trailer' and 'summary' attributes

### PR DESCRIPTION
**Pull request by mkanet**
@dylandoamaral this PR is a surprise! 😊

Added `trailer` and `summary` attributes (from TMDB API) to trakt sensors; leveraging Upcoming Media Card's newest interactive features!

**Description:**
- Clicking with your mouse or touching with your finger any trakt show/movie in Upcoming Media Card (that has a `trailer` attribute) will playback the related video trailer.  `enable_trailers: true` to enable.
- Hovering your mouse cursor over _(or long-touch on a touch screen)_ on any show/movie (that has a `summary` attribute) will display a tooltip with the related summary/description.  `enable_tooltips: true` to enable.

<br>

Example YAML code to enable both features:
```yaml
type: custom:upcoming-media-card
entity: sensor.trakt_anticipated_shows
title: Anticipated Shows
image_style: fanart
enable_tooltips: true
enable_trailers: true
```
<br>

**Example video showing both features in action:😎**

Description

Example attribute data:
**sensor.trakt_anticipated_movies**
```
data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $rating - $runtime
    line4_default: $number - $studio
    icon: mdi:arrow-down-bold
  - title: Deadpool & Wolverine
    poster: https://image.tmdb.org/t/p/w500/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg
    fanart: https://image.tmdb.org/t/p/w500/dvBCdCohwWbsP5qAaglOXagDMtk.jpg
    genres:
      - Science Fiction
      - Action
      - Comedy
    studio: Marvel Studios
    trailer: https://www.youtube.com/watch?v=73_1biulkYk
    summary: >-
      A listless Wade Wilson toils away in civilian life with his days as the
      morally flexible mercenary, Deadpool, behind him. But when his homeworld
      faces an existential threat, Wade must reluctantly suit-up again with an
      even more reluctant Wolverine.
    runtime: 127
    release: $day, $date $time
    airdate: "2024-07-24T00:00:00Z"
```

### CODE REVIEW

**Comment by dylandoamaral** [comment]
This is really cool, I am not in holliday anymore, will look after work !

**Comment by mkanet** [comment]
Hi, I currently sick. As soon as I feel better, I will look into this. FYI: I submited 2 separate PRs. The first PR includes the new Anticipated sensors. The second PR adds the `trailer` and `summary` attributes. If it is not like that, I must have made a mistake when pushing them out.

**Comment by dylandoamaral** [comment]
Hello @mkanet, I hope you feel better soon! Take care, and I look forward to hearing from you when you're well.

**Comment by mkanet** [comment]
@dylandoamaral, Sorry I hadn't gotten back to you on this.  Do you think its okay if I just submit a single PR with both features included (with everything working)?  All you have to do is merge it.  The latest PR accidentally included both features in the same PR; which confused you.  **I know this is not how you prefer to submit PRs.  I am truly sorry**  I am hoping you would make this one exception to allow me to submit a single PR with both features included.  Otherwise, it would take me very long to redo the code changes so they are in 2 separate PRs.

**Comment by dylandoamaral** [comment]
I did this one myself, you only need to fix the second one.

**Pull request closed without merging**
