### PR TITLE
feat: add deep link attribute

### LINKED ISSUE #115: Add deep_link attribute
Upcoming-media-card supports deep links to show pages.

As a user, I'd like to be able to click cards in the upcoming list to take me to the Trakt page on that show.

### PR DESCRIPTION
**Pull request by dylandoamaral**
close #115

### CODE REVIEW

**Comment by doctorkb** [comment]
Thanks!  I'm happy to test this if you can put it in a release (or "pre-release") for HACS...

**Comment by dylandoamaral** [comment]
I will add another commit tonight and do the release !

**Comment by doctorkb** [comment]
This works GREAT! Thank you!

As a troubleshooting point that you may run into... HACS has an old upcoming-media-card repo.  You have to manually add the new one: https://github.com/custom-cards/upcoming-media-card see: https://github.com/custom-cards/upcoming-media-card/issues/99#issuecomment-2272457355

Now for an even better if... the deep link linked directly to the episode, not just the show. 🙂

**Comment by dylandoamaral** [comment]
It may be interesting for you to do it yourself and make a PR, it is just one line of code ;)

**Comment by doctorkb** [comment]
You're right, I could probably figure out the code.  But I don't have the several hours to familiarize myself with git and building the test environment so I don't have to be restarting my normal HA instance to test and perfect that little bit of code.

I appreciate what you've done so far -- if I've asked too much, I'm sorry. I just thought I'd add the suggestion for improvement.

**Pull request merged**
