### PR TITLE
[Feature] Trakt List Sensor

### LINKED ISSUE #74: Trakt List Sensor
I would love to be able to pull movies/shows from a specified trakt list

API endpoint: https://api.trakt.tv/lists/{id}/items/{type}

It would also be nice to have a sort feature

Something like:

```
sensors:
  lists:
    <custom list name for entity>:
      id: <list id>
      type: 'movies' or 'show' (optional)
      sort_by: 'rank' or 'added' (optional)
      sort_order: 'asc' or 'desc' (optional)
```

### PR DESCRIPTION
**Pull request by bryan-stewart**
I threw together a list sensor implementation. I'll be honest, I'm not familiar with python but the integration was pretty straight forward. 

sensor is configured like so:

```
sensors:
  list:
    - id: <list id>
      type: 'movies' or 'show' or 'all' (optional)
      sort_by: 'rank' or 'added' or 'released' (optional)
      sort_order: 'asc' or 'desc' (optional)
      max_medias: <int> (optional) default is 30
```

I coded for myself with no intention to pull request so if it is no good, no hard feelings.

Resolves #74

### CODE REVIEW

**Comment by dylandoamaral** [comment]
Thanks for the PR ! I will check it when I have time.

**Comment by poudenes** [comment]
Any update about this feature? Seems very nice and handy!

**Comment by dylandoamaral** [comment]
Hi I will check it soon, it seems to be a popular request will see it. Sorry for the waiting time.

**Comment by dylandoamaral** [comment]
Supersed by #107 

Sorry should have been merge long ago, it will be supersed but I will credit you too for sure. Thanks !

**Pull request closed without merging**
