### PR TITLE
refactor: make trakt integration fast

### PR DESCRIPTION
**Pull request by dylandoamaral**
@Anrolosia sorry to buther you but can you check if this is ok with the next_to_watch sensors (and overall if everything is ok), it should improve the performance drastically.

### CODE REVIEW

**Comment by Anrolosia** [comment]
@dylandoamaral I've just tested it and it doesn't seems to work:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/trakt_tv/sensor.py", line 128, in state
    return max([len(self.data) - 1, 0])
                    ^^^^^^^^^
  File "/config/custom_components/trakt_tv/sensor.py", line 120, in data
    if self.medias:
       ^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/sensor.py", line 106, in medias
    return self.coordinator.data.get(self.source, {}).get(self.trakt_kind, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'get'
```
I could fix it but I need to run for my training, I could take a look later if you want

**Comment by Anrolosia** [comment]
If it helps, there is my config, pretty straight forward:
```
trakt_tv:
  language: fr
  timezone: America/Montreal
  sensors:
    next_to_watch:
      only_aired:
        max_medias: 20
      only_upcoming:
        max_medias: 20
```

**Comment by dylandoamaral** [comment]
Indeed, it should be fixed now, thank you for your check !

**Comment by Anrolosia** [comment]
Hello @dylandoamaral , it's working on my side.
Side note: I don't feel it's faster than your latest build, but it might be just a feeling :)
Nice job! Thank you

**Comment by dylandoamaral** [comment]
> Hello @dylandoamaral , it's working on my side. Side note: I don't feel it's faster than your latest build, but it might be just a feeling :) Nice job! Thank you

It should reduce queries by two but indeed it is not that much

**Pull request merged**
